### ISSUE TITLE
solution for non-youtube videos

### ISSUE THREAD

**Issue by YoColdRain** [virajkanwade/plugin.video.zeetv#1]
do you need solution for non-youtube links?

**Comment by virajkanwade** [comment]
What?

**Comment by virajkanwade** [comment]
This is for issues with the plugin. Not for marketing. Please keep it as such.

**Comment by YoColdRain** [comment]
Ok hotshot, what did I market?  I wanted to know whether you wanted solution for some videos which wouldn't work with your addon, like here
http://www.zeetv.com/shows/yeh-vaada-raha/video/yeh-vaada-raha-episode-2-september-22-2015-full-episode.html
and whether you want solution for that...

**Comment by virajkanwade** [comment]
So open an issue stating it does not play that link.

Anyways, this is an opensource project. You are free to fork and submit a PR.

And just think about what would anybody think if you just create an issue without mentioning any issue with a question which seems like, do you need help. It indirectly says 'i can fix it (for money)'

**Comment by virajkanwade** [comment]
On github, people just fork and submit a PR. Nobody asks if you need help. :)

**Comment by YoColdRain** [comment]
really? I'm going to scour github for money? All I cared was whether you wanted the solution for your plugin since I installed it and didnt work for some videos.  You obviously have more experience than I do by looking at your profile, and I was hesitant whether you had solution or not.

**Comment by virajkanwade** [comment]
Don't worry. Just fix it and submit a PR. If you submit a PR, nobody is going to frown at you. But if you ask such a question, surely people will react the same way I did :)

**Comment by virajkanwade** [comment]
I submitted a PR for docker and we were going to and for for almost 2 weeks. And all I have done on docker so far is 'Hello World' :D

**Comment by virajkanwade** [comment]
Encryption! Man, zeetv is improving.

**Comment by YoColdRain** [comment]
maybe not everyone comes for the money... anyways, look at this jsfiddle http://jsfiddle.net/rvgbnyjp/2/ , I think you can implement python solution out of it, if you need AES file for python, its on my repo.  pyaes.py

good luck.

**Comment by YoColdRain** [comment]
above fiddle is not for same encryption you posted on #2
