### ISSUE TITLE
Fails for latest video

### ISSUE THREAD

**Issue by virajkanwade** [virajkanwade/plugin.video.zeetv#2]
http://www.zeetv.com/shows/yeh-vaada-raha/video/yeh-vaada-raha-episode-2-september-22-2015-full-episode.html

**Comment by virajkanwade** [comment]
var dailytoday = 'YRHFHGFJHGJG';
var subject = '{"ct":"N2obK+Lu4b4tr5MfqBADSNT2tp27NdSZrVbOcdiUKWwx09Fg5lcKnze\/aljSvVTx2oNDoRscnG8GGjpRvKTd+eeNeghHy6KjSVv6HUEsMm7wzthU4jYWns4fTRJP0zIXgHLl3SeTolMCWYEBOwgNfzWPCMVy6kid8D7BjMdJu5yCeqEgo5eaAL5yReqez9amqWzzbk5VfTrH5DOI0R7It7gyDhw5ut7GcOpBtkI+x3GI1dlR9dZtd98ex16wmeN0ab88J7Et+jYete9ra7Ead\/0zakcVZ1\/X4k9Ysuo8bL6K6Xy8ywh1J1TUKZV5Ux3XOlna4VrjCkgec5Y72a8b+K\/VU\/fQuj0SxH3FimCUARM=","iv":"4dba5f303f69c6ddbe8a079d3ab62329","s":"e881d870e0389879"}';
var dramavalue = JSON.parse(CryptoJS.AES.decrypt(subject, dailytoday, {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8));

**Comment by virajkanwade** [comment]
https://code.google.com/p/crypto-js/#The_Cipher_Output
https://gist.github.com/sekondus/4322469
https://gist.github.com/marcoslin/8026990
https://github.com/ricmoo/pyaes

**Comment by ykhehra1** [comment]
Have a look!  http://stackoverflow.com/questions/14958103/how-to-decrypt-message-with-cryptojs-aes-i-have-a-working-ruby-example


"This works for decryption using javascript.

<script 
      src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js">
             </script>

var decrypted = CryptoJS.AES.decrypt(data,key).toString(CryptoJS.enc.Utf8);
Guess I am a little late to the party.
"

**Comment by virajkanwade** [comment]
http://stackoverflow.com/questions/27677236/encryption-in-javascript-and-decryption-with-php/27678978#27678978

**Comment by virajkanwade** [comment]
Fixed in v0.0.5
